### ISSUE TITLE
.dat file format

### ISSUE THREAD

**Issue by sgbaird** [Yufeng-shen/TJ2GBE#1]
Could you explain the format of the .dat file?

**Comment by sgbaird** [comment]
Just saw inside comments of Reconstruction.py:
    Input: triples.dat, wrote from the fortran program Torq_trn
                size=[numTJ*8,]
                In each group, the data is [TJ directon, EA1, GB1, EA2, GB2, EA3, GB3]

(BTW I think that it should be Torq_gen, not Torq_trn, see other [GitHub issue](https://github.com/Yufeng-shen/TJ2GBE/issues/3#issue-682298309))

e.g.
 1
          -0.0000  -0.0000  -1.0000
             49.6     22.6    315.4
           0.9897   0.1435  -0.0000
            201.1     28.0    129.9
          -0.4983   0.8670  -0.0000
            304.5     21.3     65.9
          -0.5704  -0.8214   0.0000

Which I believe is:
1) triple line orientation (Cartesian vector)
2) Grain 1 Euler Angles (in degrees)
3) GB 1-2 Normal (Cartesian coordinates, normal pointing towards grain 2 in crystal reference frame of grain 1)
4) Grain 2 Euler Angles
5) GB 2-3 Normal
6) Grain 3 Euler Angles
7) GB 3-1 Normal

Is that correct?

**Comment by Yufeng-shen** [comment]
You are right, it is Torq_gen. And your interpretation of .dat file format is also correct.

**Comment by sgbaird** [comment]
Thank you!

**Comment by Yufeng-shen** [comment]
Sorry I was wrong about the interpretation. 
For each triple junction, the 1st line is the direction of the triple junction (represented by a unit vector), 2nd,4th,6th lines are Euler angles of grain1 grain2 grain3 (Bunge convention), 3rd, 5th, 7th lines are normal vector of grain boundaries, GB1, GB2, GB3. Everything is in the sample frame. GB1 is between grain2 and grain3, GB2 is between grain3 and grain1, GB3 is between grain1 and grain2. 
So in your comment, line 3 should be GB 2-3 Normal, in sample frame.

**Comment by sgbaird** [comment]
Ok, good to know. So then:

triple line direction (sample frame, Cartesian unit vector)
Grain 1 Euler Angles (sample frame, in degrees)
GB 1 (grain 2 --> grain 3) Normal (Cartesian normal vector in sample frame, pointing from grain 2 towards grain 3)
Grain 2 Euler Angles
GB 2 (grain 3 --> grain 1) Normal
Grain 3 Euler Angles
GB 3 (grain 1 --> grain 2) Normal

Really appreciate the help!

**Comment by Yufeng-shen** [comment]
That's right.
