### ISSUE TITLE
What is the source of the example triple junction data?

### ISSUE THREAD

**Issue by sgbaird** [Yufeng-shen/TJ2GBE#2]
I.e. where do those 30,000 triple junctions come from? Could you provide a link if it's to something other than a randomly generated dataset?

Also, how is the ground truth defined/where does this come from?

**Comment by Yufeng-shen** [comment]
I just uploaded the Fortran code (which is used for generating the triple junctions), and the README.md file is updated for this Fortran code.

**Comment by Yufeng-shen** [comment]
The ground truth is defined in  "Determining grain boundary energies from triple junction geometries without discretizing the five-parameter space" Acta Materialia 166, 126-134 (2019). The Fortran code can generate the ground truth along with the triple junctions. You can read the source code for more details.

**Comment by sgbaird** [comment]
Awesome! Thank you.
