### ISSUE TITLE
Generating a triples.dat file

### ISSUE THREAD

**Issue by sgbaird** [Yufeng-shen/TJ2GBE#3]
Reconstruction.py states that triples.dat is produced from a fortran program Torq_trn.

The README [here](http://mimp.materials.cmu.edu/~gr20/stereology/3D_programs/energy/Read.me.txt) describes that 'triples.dat' is produced via 'Torq_gen.exe', however this executable isn't in the [directory](http://mimp.materials.cmu.edu/~gr20/stereology/3D_programs/energy/) that the README file is in. I see torq_rec and torq_trn_ev, but can't seem to find "Torq_gen" or even "Torq_trn". Am I just missing it from somewhere in those directories, is it under a different filename, or is it somewhere else?

**Comment by Yufeng-shen** [comment]
I will add the Torq_gen and other dependencies in this repository, so that users can generate the simulated triples.dat by themselves.

**Comment by sgbaird** [comment]
That would be great. Thank you!
